[INFO] [2021-06-15 22:03:25,152] [3760:140577387210560] - task_executor.py[line:313]: report task 2021061522031652853221_dataio_0 0 guest 9999 to driver
[INFO] [2021-06-15 22:03:25,153] [3760:140577387210560] - control_client.py[line:42]: request update job 2021061522031652853221 task 2021061522031652853221_dataio_0 0 on guest 9999
[DEBUG] [2021-06-15 22:03:25,553] [3760:140577387210560] - _federation.py[line:15]: [federation.standalone]init federation: standalone_session=<fate_arch._standalone.Session object at 0x7fdab8f4a748>, federation_session_id=2021061522031652853221_dataio_0_0, party=Party(role=guest, party_id=9999)
[DEBUG] [2021-06-15 22:03:25,563] [3760:140577387210560] - _federation.py[line:23]: [federation.standalone]init federation context done
[INFO] [2021-06-15 22:03:25,563] [3760:140577387210560] - task_executor.py[line:150]: Run 2021061522031652853221 dataio_0 2021061522031652853221_dataio_0 guest 9999 task
[INFO] [2021-06-15 22:03:25,564] [3760:140577387210560] - task_executor.py[line:151]: Component parameters on party {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': True, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense', 'need_run': True}, 'dsl_path': './examples/LDPDev/dsl/v2/hetero_secureboost/test_secureboost_train_dsl.json', 'component_parameters': {'role': {'host': {'0': {'reader_1': {'table': {'name': 'breast_hetero_host', 'namespace': 'experiment'}}, 'reader_0': {'table': {'name': 'default_credit_hetero_host', 'namespace': 'experiment'}}, 'dataio_0': {'with_label': False}, 'dataio_1': {'with_label': False}}}, 'guest': {'0': {'reader_1': {'table': {'name': 'breast_hetero_guest', 'namespace': 'experiment'}}, 'reader_0': {'table': {'name': 'default_credit_hetero_guest', 'namespace': 'experiment'}}, 'dataio_0': {'with_label': True, 'output_format': 'dense'}, 'dataio_1': {'with_label': True, 'output_format': 'dense'}}}}, 'common': {'hetero_secure_boost_0': {'task_type': 'classification', 'objective_param': {'objective': 'cross_entropy'}, 'num_trees': 3, 'validation_freqs': 1, 'encrypt_param': {'method': 'iterativeAffine'}, 'tree_param': {'max_depth': 3}}, 'evaluation_0': {'eval_type': 'binary'}}}, 'initiator': {'role': 'guest', 'party_id': 9999}, 'dsl_version': 2, 'job_parameters': {'job_type': 'predict', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {'computing': {'nodes': 1, 'cores_per_node': 20}, 'federation': {'nodes': 1, 'cores_per_node': 20}, 'storage': {'nodes': 1, 'cores_per_node': 20}}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'guest-9999#host-9998#model', 'model_version': '2021061522023585229020', 'eggroll_run': {'eggroll.session.processors.per.node': 4}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_memory_per_node': 0, 'if_initiator_baseline': False, 'task_cores_per_node': 4, 'request_task_cores': 4, 'task_nodes': 1}}, 'conf_path': './examples/LDPDev/test_predict_conf.json', 'role': {'host': [9998], 'guest': [9999]}, 'local': {'role': 'guest', 'party_id': 9999}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO', 'output_data_name': ['data']}
[INFO] [2021-06-15 22:03:25,564] [3760:140577387210560] - task_executor.py[line:152]: Task input dsl {'data': {'data': ['reader_0.data']}, 'model': ['pipeline.dataio_0.model']}
[INFO] [2021-06-15 22:03:25,565] [3760:140577387210560] - tracker_client.py[line:150]: Request read job 2021061522031652853221 task None None on guest 9999 data data info
[DEBUG] [2021-06-15 22:03:25,594] [3760:140577387210560] - apsw_ext.py[line:109]: ('SELECT "t1"."f_create_date", "t1"."f_update_date", "t1"."f_name", "t1"."f_namespace", "t1"."f_address", "t1"."f_engine", "t1"."f_type", "t1"."f_options", "t1"."f_partitions", "t1"."f_id_delimiter", "t1"."f_in_serialized", "t1"."f_have_head", "t1"."f_schema", "t1"."f_count", "t1"."f_part_of_data", "t1"."f_description", "t1"."f_create_time", "t1"."f_update_time" FROM "t_storage_table_meta" AS "t1" WHERE (("t1"."f_name" = ?) AND ("t1"."f_namespace" = ?))', ['7f517042ce2511eba0000242ac110002', 'output_data_2021061522031652853221_reader_0_0'])
[INFO] [2021-06-15 22:03:25,611] [3760:140577387210560] - task_executor.py[line:269]: load computing table use 4
[INFO] [2021-06-15 22:03:26,151] [3760:140577387210560] - pipelined_model.py[line:185]: parse DataIOMeta proto object normal
[INFO] [2021-06-15 22:03:26,158] [3760:140577387210560] - pipelined_model.py[line:185]: parse DataIOParam proto object normal
[DEBUG] [2021-06-15 22:03:26,163] [3760:140577387210560] - component_properties.py[line:73]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': True, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense', 'need_run': True}, 'dsl_path': './examples/LDPDev/dsl/v2/hetero_secureboost/test_secureboost_train_dsl.json', 'component_parameters': {'role': {'host': {'0': {'reader_1': {'table': {'name': 'breast_hetero_host', 'namespace': 'experiment'}}, 'reader_0': {'table': {'name': 'default_credit_hetero_host', 'namespace': 'experiment'}}, 'dataio_0': {'with_label': False}, 'dataio_1': {'with_label': False}}}, 'guest': {'0': {'reader_1': {'table': {'name': 'breast_hetero_guest', 'namespace': 'experiment'}}, 'reader_0': {'table': {'name': 'default_credit_hetero_guest', 'namespace': 'experiment'}}, 'dataio_0': {'with_label': True, 'output_format': 'dense'}, 'dataio_1': {'with_label': True, 'output_format': 'dense'}}}}, 'common': {'hetero_secure_boost_0': {'task_type': 'classification', 'objective_param': {'objective': 'cross_entropy'}, 'num_trees': 3, 'validation_freqs': 1, 'encrypt_param': {'method': 'iterativeAffine'}, 'tree_param': {'max_depth': 3}}, 'evaluation_0': {'eval_type': 'binary'}}}, 'initiator': {'role': 'guest', 'party_id': 9999}, 'dsl_version': 2, 'job_parameters': {'job_type': 'predict', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {'computing': {'nodes': 1, 'cores_per_node': 20}, 'federation': {'nodes': 1, 'cores_per_node': 20}, 'storage': {'nodes': 1, 'cores_per_node': 20}}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'guest-9999#host-9998#model', 'model_version': '2021061522023585229020', 'eggroll_run': {'eggroll.session.processors.per.node': 4}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_memory_per_node': 0, 'if_initiator_baseline': False, 'task_cores_per_node': 4, 'request_task_cores': 4, 'task_nodes': 1}}, 'conf_path': './examples/LDPDev/test_predict_conf.json', 'role': {'host': [9998], 'guest': [9999]}, 'local': {'role': 'guest', 'party_id': 9999}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO', 'output_data_name': ['data']}
[DEBUG] [2021-06-15 22:03:26,163] [3760:140577387210560] - component_properties.py[line:80]: need_run: True, need_cv: False
[WARNING] [2021-06-15 22:03:26,164] [3760:140577387210560] - data_io.py[line:855]: DataIO is deprecated, and will be removed in 1.7, use DataTransform module instead
[DEBUG] [2021-06-15 22:03:26,164] [3760:140577387210560] - component_properties.py[line:102]: parse_dsl_args data_sets: {'reader_0': {'data': [<fate_arch.computing.standalone._table.Table object at 0x7fda741a2828>]}}
[DEBUG] [2021-06-15 22:03:26,164] [3760:140577387210560] - component_properties.py[line:112]: [Data Parser], has_train_data: False
[DEBUG] [2021-06-15 22:03:26,165] [3760:140577387210560] - component_properties.py[line:112]: [Data Parser], has_eval_data: False
[DEBUG] [2021-06-15 22:03:26,165] [3760:140577387210560] - component_properties.py[line:112]: [Data Parser], has_validate_data: False
[DEBUG] [2021-06-15 22:03:26,165] [3760:140577387210560] - component_properties.py[line:112]: [Data Parser], has_test_data: False
[DEBUG] [2021-06-15 22:03:26,165] [3760:140577387210560] - component_properties.py[line:118]: [Data Parser], has_normal_data: True
[DEBUG] [2021-06-15 22:03:26,165] [3760:140577387210560] - component_properties.py[line:179]: Input data_sets: {'reader_0': {'data': [<fate_arch.computing.standalone._table.Table object at 0x7fda741a2828>]}}
[DEBUG] [2021-06-15 22:03:26,165] [3760:140577387210560] - component_properties.py[line:189]: data_dict: {'data': [<fate_arch.computing.standalone._table.Table object at 0x7fda741a2828>]}
[DEBUG] [2021-06-15 22:03:26,166] [3760:140577387210560] - component_properties.py[line:192]: data_list: <fate_arch.computing.standalone._table.Table object at 0x7fda741a2828>
[DEBUG] [2021-06-15 22:03:26,170] [3760:140577387210560] - profile.py[line:84]: [computing#41d092c3c4]function_stack: [component_properties.py:225]extract_input_data <-[component_properties.py:238]extract_running_rules <-[model_base.py:87]run
[DEBUG] [2021-06-15 22:03:26,171] [3760:140577387210560] - profile.py[line:87]: [computing#41d092c3c4]start
[DEBUG] [2021-06-15 22:03:26,173] [3760:140577387210560] - profile.py[line:93]: [computing#41d092c3c4]done, elapse: 0.0030536651611328125, function: count(self: Table(partition=4)) -> int
[DEBUG] [2021-06-15 22:03:26,174] [3760:140577387210560] - component_properties.py[line:231]: train_data: None, validate_data: None, test_data: None, data: {'reader_0.data': <fate_arch.computing.standalone._table.Table object at 0x7fda741a2828>}
[DEBUG] [2021-06-15 22:03:26,174] [3760:140577387210560] - model_base.py[line:88]: running_funcs: [<bound method DataIO.load_model of <federatedml.util.data_io.DataIO object at 0x7fda741cf630>>, <function ModelBase.extract_data at 0x7fda74193400>, <bound method ModelBase.set_flowid of <federatedml.util.data_io.DataIO object at 0x7fda741cf630>>, <bound method DataIO.transform of <federatedml.util.data_io.DataIO object at 0x7fda741cf630>>]
[DEBUG] [2021-06-15 22:03:26,174] [3760:140577387210560] - model_base.py[line:340]: In extract_data, data input: {'reader_0.data': <fate_arch.computing.standalone._table.Table object at 0x7fda741a2828>}
[DEBUG] [2021-06-15 22:03:26,175] [3760:140577387210560] - model_base.py[line:97]: func: <bound method DataIO.transform of <federatedml.util.data_io.DataIO object at 0x7fda741cf630>>
[INFO] [2021-06-15 22:03:26,175] [3760:140577387210560] - data_io.py[line:118]: start to read dense data and change data to instance
[DEBUG] [2021-06-15 22:03:26,176] [3760:140577387210560] - profile.py[line:84]: [computing#7a5e4c5159]function_stack: [abnormal_detection.py:27]empty_table_detection <-[data_io.py:120]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 22:03:26,176] [3760:140577387210560] - profile.py[line:87]: [computing#7a5e4c5159]start
[DEBUG] [2021-06-15 22:03:26,178] [3760:140577387210560] - profile.py[line:93]: [computing#7a5e4c5159]done, elapse: 0.002325773239135742, function: count(self: Table(partition=4)) -> int
[DEBUG] [2021-06-15 22:03:26,179] [3760:140577387210560] - data_io.py[line:75]: header is y,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12
[DEBUG] [2021-06-15 22:03:26,179] [3760:140577387210560] - data_io.py[line:76]: sid_name is id
[DEBUG] [2021-06-15 22:03:26,180] [3760:140577387210560] - profile.py[line:84]: [computing#9133971679]function_stack: [data_overview.py:123]get_data_shape <-[data_io.py:131]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 22:03:26,180] [3760:140577387210560] - profile.py[line:87]: [computing#9133971679]start
[DEBUG] [2021-06-15 22:03:26,183] [3760:140577387210560] - profile.py[line:93]: [computing#9133971679]done, elapse: 0.0024416446685791016, function: first(self: Table(partition=4)) -> tuple
[DEBUG] [2021-06-15 22:03:26,184] [3760:140577387210560] - profile.py[line:84]: [computing#2b2e549bd4]function_stack: [data_io.py:136]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 22:03:26,184] [3760:140577387210560] - profile.py[line:87]: [computing#2b2e549bd4]start
[DEBUG] [2021-06-15 22:03:27,194] [3760:140577387210560] - profile.py[line:93]: [computing#2b2e549bd4]done, elapse: 1.0105962753295898, function: mapValues(self: Table(partition=4), func: function) -> Table(partition=4)
[DEBUG] [2021-06-15 22:03:27,196] [3760:140577387210560] - profile.py[line:84]: [computing#4509abf693]function_stack: [data_io.py:139]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 22:03:27,196] [3760:140577387210560] - profile.py[line:87]: [computing#4509abf693]start
[DEBUG] [2021-06-15 22:03:28,119] [3760:140577387210560] - profile.py[line:93]: [computing#4509abf693]done, elapse: 0.9233477115631104, function: mapValues(self: Table(partition=4), func: function) -> Table(partition=4)
[DEBUG] [2021-06-15 22:03:28,121] [3760:140577387210560] - profile.py[line:84]: [computing#0aeead51ce]function_stack: [io_check.py:28]_func <-[data_io.py:148]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 22:03:28,121] [3760:140577387210560] - profile.py[line:87]: [computing#0aeead51ce]start
[DEBUG] [2021-06-15 22:03:28,126] [3760:140577387210560] - profile.py[line:93]: [computing#0aeead51ce]done, elapse: 0.005315065383911133, function: count(self: Table(partition=4)) -> int
[DEBUG] [2021-06-15 22:03:28,127] [3760:140577387210560] - abnormal_detection.py[line:81]: schema is {'header': ['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12'], 'sid_name': 'id', 'label_name': 'y'}
[DEBUG] [2021-06-15 22:03:28,127] [3760:140577387210560] - abnormal_detection.py[line:85]: header is ['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12']
[DEBUG] [2021-06-15 22:03:28,127] [3760:140577387210560] - abnormal_detection.py[line:95]: sid_name is id
[DEBUG] [2021-06-15 22:03:28,127] [3760:140577387210560] - abnormal_detection.py[line:100]: label_name is y
[DEBUG] [2021-06-15 22:03:28,128] [3760:140577387210560] - profile.py[line:84]: [computing#82552c8a50]function_stack: [data_io.py:224]gen_data_instance <-[data_io.py:175]transform <-[io_check.py:31]_func <-[data_io.py:148]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 22:03:28,129] [3760:140577387210560] - profile.py[line:87]: [computing#82552c8a50]start
[DEBUG] [2021-06-15 22:03:30,673] [3760:140577387210560] - profile.py[line:93]: [computing#82552c8a50]done, elapse: 2.544586658477783, function: join(self: Table(partition=4), other: Table(partition=4), func: function) -> Table(partition=4)
[DEBUG] [2021-06-15 22:03:30,674] [3760:140577387210560] - profile.py[line:84]: [computing#fba26d134a]function_stack: [io_check.py:34]_func <-[data_io.py:148]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 22:03:30,675] [3760:140577387210560] - profile.py[line:87]: [computing#fba26d134a]start
[DEBUG] [2021-06-15 22:03:30,678] [3760:140577387210560] - profile.py[line:93]: [computing#fba26d134a]done, elapse: 0.003893136978149414, function: count(self: Table(partition=4)) -> int
[DEBUG] [2021-06-15 22:03:30,679] [3760:140577387210560] - io_check.py[line:35]: num row of input: 30000 -> num row of output: 0
[ERROR] [2021-06-15 22:03:30,679] [3760:140577387210560] - task_executor.py[line:191]: num row of input(30000) not equals to num row of output(0)
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/task_executor.py", line 168, in run_task
    run_object.run(component_parameters_on_party, task_run_args)
  File "/fate/python/federatedml/model_base.py", line 98, in run
    this_data_output = func(*real_param)
  File "/fate/python/federatedml/util/data_io.py", line 895, in transform
    return self.reader.read_data(data_inst, "transform")
  File "/fate/python/federatedml/util/data_io.py", line 148, in read_data
    data_instance = self.transform(input_data_features, input_data_labels)
  File "/fate/python/federatedml/util/io_check.py", line 38, in _func
    f"num row of input({input_count}) not equals to num row of output({output_count})")
OSError: num row of input(30000) not equals to num row of output(0)
