[INFO] [2021-06-15 21:56:45,747] [3074:139995760379712] - task_executor.py[line:313]: report task 2021061521563264143218_dataio_0 0 host 9998 to driver
[INFO] [2021-06-15 21:56:45,748] [3074:139995760379712] - control_client.py[line:42]: request update job 2021061521563264143218 task 2021061521563264143218_dataio_0 0 on host 9998
[DEBUG] [2021-06-15 21:56:46,157] [3074:139995760379712] - _federation.py[line:15]: [federation.standalone]init federation: standalone_session=<fate_arch._standalone.Session object at 0x7f534b7eb9b0>, federation_session_id=2021061521563264143218_dataio_0_0, party=Party(role=host, party_id=9998)
[DEBUG] [2021-06-15 21:56:46,165] [3074:139995760379712] - _federation.py[line:23]: [federation.standalone]init federation context done
[INFO] [2021-06-15 21:56:46,165] [3074:139995760379712] - task_executor.py[line:150]: Run 2021061521563264143218 dataio_0 2021061521563264143218_dataio_0 host 9998 task
[INFO] [2021-06-15 21:56:46,166] [3074:139995760379712] - task_executor.py[line:151]: Component parameters on party {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': False, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense', 'need_run': True}, 'dsl_path': './examples/LDPDev/dsl/v2/hetero_secureboost/test_secureboost_train_dsl.json', 'job_parameters': {'job_type': 'predict', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {'computing': {'nodes': 1, 'cores_per_node': 20}, 'federation': {'nodes': 1, 'cores_per_node': 20}, 'storage': {'nodes': 1, 'cores_per_node': 20}}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'guest-9999#host-9998#model', 'model_version': '2021061521542761899517', 'eggroll_run': {'eggroll.session.processors.per.node': 4}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_memory_per_node': 0, 'if_initiator_baseline': False, 'task_cores_per_node': 4, 'request_task_cores': 4, 'task_nodes': 1}}, 'component_parameters': {'common': {'hetero_secure_boost_0': {'task_type': 'classification', 'objective_param': {'objective': 'cross_entropy'}, 'num_trees': 3, 'validation_freqs': 1, 'encrypt_param': {'method': 'iterativeAffine'}, 'tree_param': {'max_depth': 3}}, 'evaluation_0': {'eval_type': 'binary'}}, 'role': {'guest': {'0': {'dataio_1': {'with_label': True, 'output_format': 'dense'}, 'reader_0': {'table': {'namespace': 'experiment', 'name': 'default_credit_hetero_guest'}}, 'dataio_0': {'with_label': True, 'output_format': 'dense'}, 'reader_1': {'table': {'name': 'breast_hetero_guest', 'namespace': 'experiment'}}}}, 'host': {'0': {'dataio_1': {'with_label': False}, 'reader_0': {'table': {'namespace': 'experiment', 'name': 'default_credit_hetero_host'}}, 'dataio_0': {'with_label': False}, 'reader_1': {'table': {'name': 'breast_hetero_host', 'namespace': 'experiment'}}}}}}, 'initiator': {'party_id': 9999, 'role': 'guest'}, 'dsl_version': 2, 'role': {'guest': [9999], 'host': [9998]}, 'conf_path': './examples/LDPDev/test_predict_conf.json', 'local': {'role': 'host', 'party_id': 9998}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO', 'output_data_name': ['data']}
[INFO] [2021-06-15 21:56:46,166] [3074:139995760379712] - task_executor.py[line:152]: Task input dsl {'model': ['pipeline.dataio_0.model'], 'data': {'data': ['reader_0.data']}}
[INFO] [2021-06-15 21:56:46,189] [3074:139995760379712] - pipelined_model.py[line:185]: parse DataIOMeta proto object normal
[INFO] [2021-06-15 21:56:46,200] [3074:139995760379712] - pipelined_model.py[line:185]: parse DataIOParam proto object normal
[INFO] [2021-06-15 21:56:46,201] [3074:139995760379712] - tracker_client.py[line:150]: Request read job 2021061521563264143218 task None None on host 9998 data data info
[DEBUG] [2021-06-15 21:56:46,218] [3074:139995760379712] - apsw_ext.py[line:109]: ('SELECT "t1"."f_create_date", "t1"."f_update_date", "t1"."f_name", "t1"."f_namespace", "t1"."f_address", "t1"."f_engine", "t1"."f_type", "t1"."f_options", "t1"."f_partitions", "t1"."f_id_delimiter", "t1"."f_in_serialized", "t1"."f_have_head", "t1"."f_schema", "t1"."f_count", "t1"."f_part_of_data", "t1"."f_description", "t1"."f_create_time", "t1"."f_update_time" FROM "t_storage_table_meta" AS "t1" WHERE (("t1"."f_name" = ?) AND ("t1"."f_namespace" = ?))', ['8fd3491ece2411eb9ef90242ac110002', 'output_data_2021061521563264143218_reader_0_0'])
[INFO] [2021-06-15 21:56:46,230] [3074:139995760379712] - task_executor.py[line:269]: load computing table use 4
[DEBUG] [2021-06-15 21:56:46,863] [3074:139995760379712] - component_properties.py[line:73]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': False, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense', 'need_run': True}, 'dsl_path': './examples/LDPDev/dsl/v2/hetero_secureboost/test_secureboost_train_dsl.json', 'job_parameters': {'job_type': 'predict', 'work_mode': 0, 'backend': 0, 'computing_engine': 'STANDALONE', 'federation_engine': 'STANDALONE', 'storage_engine': 'STANDALONE', 'engines_address': {'computing': {'nodes': 1, 'cores_per_node': 20}, 'federation': {'nodes': 1, 'cores_per_node': 20}, 'storage': {'nodes': 1, 'cores_per_node': 20}}, 'federated_mode': 'SINGLE', 'task_parallelism': 1, 'computing_partitions': 4, 'federated_status_collect_type': 'PULL', 'model_id': 'guest-9999#host-9998#model', 'model_version': '2021061521542761899517', 'eggroll_run': {'eggroll.session.processors.per.node': 4}, 'spark_run': {}, 'rabbitmq_run': {}, 'pulsar_run': {}, 'adaptation_parameters': {'task_memory_per_node': 0, 'if_initiator_baseline': False, 'task_cores_per_node': 4, 'request_task_cores': 4, 'task_nodes': 1}}, 'component_parameters': {'common': {'hetero_secure_boost_0': {'task_type': 'classification', 'objective_param': {'objective': 'cross_entropy'}, 'num_trees': 3, 'validation_freqs': 1, 'encrypt_param': {'method': 'iterativeAffine'}, 'tree_param': {'max_depth': 3}}, 'evaluation_0': {'eval_type': 'binary'}}, 'role': {'guest': {'0': {'dataio_1': {'with_label': True, 'output_format': 'dense'}, 'reader_0': {'table': {'namespace': 'experiment', 'name': 'default_credit_hetero_guest'}}, 'dataio_0': {'with_label': True, 'output_format': 'dense'}, 'reader_1': {'table': {'name': 'breast_hetero_guest', 'namespace': 'experiment'}}}}, 'host': {'0': {'dataio_1': {'with_label': False}, 'reader_0': {'table': {'namespace': 'experiment', 'name': 'default_credit_hetero_host'}}, 'dataio_0': {'with_label': False}, 'reader_1': {'table': {'name': 'breast_hetero_host', 'namespace': 'experiment'}}}}}}, 'initiator': {'party_id': 9999, 'role': 'guest'}, 'dsl_version': 2, 'role': {'guest': [9999], 'host': [9998]}, 'conf_path': './examples/LDPDev/test_predict_conf.json', 'local': {'role': 'host', 'party_id': 9998}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO', 'output_data_name': ['data']}
[DEBUG] [2021-06-15 21:56:46,864] [3074:139995760379712] - component_properties.py[line:80]: need_run: True, need_cv: False
[WARNING] [2021-06-15 21:56:46,864] [3074:139995760379712] - data_io.py[line:855]: DataIO is deprecated, and will be removed in 1.7, use DataTransform module instead
[DEBUG] [2021-06-15 21:56:46,864] [3074:139995760379712] - component_properties.py[line:102]: parse_dsl_args data_sets: {'reader_0': {'data': [<fate_arch.computing.standalone._table.Table object at 0x7f53087384a8>]}}
[DEBUG] [2021-06-15 21:56:46,864] [3074:139995760379712] - component_properties.py[line:112]: [Data Parser], has_train_data: False
[DEBUG] [2021-06-15 21:56:46,865] [3074:139995760379712] - component_properties.py[line:112]: [Data Parser], has_eval_data: False
[DEBUG] [2021-06-15 21:56:46,865] [3074:139995760379712] - component_properties.py[line:112]: [Data Parser], has_validate_data: False
[DEBUG] [2021-06-15 21:56:46,865] [3074:139995760379712] - component_properties.py[line:112]: [Data Parser], has_test_data: False
[DEBUG] [2021-06-15 21:56:46,865] [3074:139995760379712] - component_properties.py[line:118]: [Data Parser], has_normal_data: True
[DEBUG] [2021-06-15 21:56:46,865] [3074:139995760379712] - component_properties.py[line:179]: Input data_sets: {'reader_0': {'data': [<fate_arch.computing.standalone._table.Table object at 0x7f53087384a8>]}}
[DEBUG] [2021-06-15 21:56:46,865] [3074:139995760379712] - component_properties.py[line:189]: data_dict: {'data': [<fate_arch.computing.standalone._table.Table object at 0x7f53087384a8>]}
[DEBUG] [2021-06-15 21:56:46,865] [3074:139995760379712] - component_properties.py[line:192]: data_list: <fate_arch.computing.standalone._table.Table object at 0x7f53087384a8>
[DEBUG] [2021-06-15 21:56:46,874] [3074:139995760379712] - profile.py[line:84]: [computing#41d092c3c4]function_stack: [component_properties.py:225]extract_input_data <-[component_properties.py:238]extract_running_rules <-[model_base.py:87]run
[DEBUG] [2021-06-15 21:56:46,875] [3074:139995760379712] - profile.py[line:87]: [computing#41d092c3c4]start
[DEBUG] [2021-06-15 21:56:46,878] [3074:139995760379712] - profile.py[line:93]: [computing#41d092c3c4]done, elapse: 0.004452943801879883, function: count(self: Table(partition=4)) -> int
[DEBUG] [2021-06-15 21:56:46,879] [3074:139995760379712] - component_properties.py[line:231]: train_data: None, validate_data: None, test_data: None, data: {'reader_0.data': <fate_arch.computing.standalone._table.Table object at 0x7f53087384a8>}
[DEBUG] [2021-06-15 21:56:46,879] [3074:139995760379712] - model_base.py[line:88]: running_funcs: [<bound method DataIO.load_model of <federatedml.util.data_io.DataIO object at 0x7f53086d4ef0>>, <function ModelBase.extract_data at 0x7f5308688378>, <bound method ModelBase.set_flowid of <federatedml.util.data_io.DataIO object at 0x7f53086d4ef0>>, <bound method DataIO.transform of <federatedml.util.data_io.DataIO object at 0x7f53086d4ef0>>]
[DEBUG] [2021-06-15 21:56:46,879] [3074:139995760379712] - model_base.py[line:340]: In extract_data, data input: {'reader_0.data': <fate_arch.computing.standalone._table.Table object at 0x7f53087384a8>}
[DEBUG] [2021-06-15 21:56:46,879] [3074:139995760379712] - model_base.py[line:97]: func: <bound method DataIO.transform of <federatedml.util.data_io.DataIO object at 0x7f53086d4ef0>>
[INFO] [2021-06-15 21:56:46,880] [3074:139995760379712] - data_io.py[line:118]: start to read dense data and change data to instance
[DEBUG] [2021-06-15 21:56:46,881] [3074:139995760379712] - profile.py[line:84]: [computing#7a5e4c5159]function_stack: [abnormal_detection.py:27]empty_table_detection <-[data_io.py:120]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 21:56:46,882] [3074:139995760379712] - profile.py[line:87]: [computing#7a5e4c5159]start
[DEBUG] [2021-06-15 21:56:46,885] [3074:139995760379712] - profile.py[line:93]: [computing#7a5e4c5159]done, elapse: 0.003882169723510742, function: count(self: Table(partition=4)) -> int
[DEBUG] [2021-06-15 21:56:46,886] [3074:139995760379712] - data_io.py[line:75]: header is x0,x1,x2,x3,x4,x5,x6,x7,x8,x9
[DEBUG] [2021-06-15 21:56:46,887] [3074:139995760379712] - data_io.py[line:76]: sid_name is id
[DEBUG] [2021-06-15 21:56:46,888] [3074:139995760379712] - profile.py[line:84]: [computing#5d186c544e]function_stack: [data_io.py:143]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 21:56:46,888] [3074:139995760379712] - profile.py[line:87]: [computing#5d186c544e]start
[DEBUG] [2021-06-15 21:56:47,870] [3074:139995760379712] - profile.py[line:93]: [computing#5d186c544e]done, elapse: 0.9811310768127441, function: mapValues(self: Table(partition=4), func: function) -> Table(partition=4)
[DEBUG] [2021-06-15 21:56:47,872] [3074:139995760379712] - profile.py[line:84]: [computing#0aeead51ce]function_stack: [io_check.py:28]_func <-[data_io.py:148]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 21:56:47,872] [3074:139995760379712] - profile.py[line:87]: [computing#0aeead51ce]start
[DEBUG] [2021-06-15 21:56:47,875] [3074:139995760379712] - profile.py[line:93]: [computing#0aeead51ce]done, elapse: 0.002981424331665039, function: count(self: Table(partition=4)) -> int
[DEBUG] [2021-06-15 21:56:47,876] [3074:139995760379712] - abnormal_detection.py[line:81]: schema is {'header': ['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9'], 'sid_name': 'id', 'label_name': 'y'}
[DEBUG] [2021-06-15 21:56:47,876] [3074:139995760379712] - abnormal_detection.py[line:85]: header is ['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9']
[DEBUG] [2021-06-15 21:56:47,876] [3074:139995760379712] - abnormal_detection.py[line:95]: sid_name is id
[DEBUG] [2021-06-15 21:56:47,876] [3074:139995760379712] - abnormal_detection.py[line:100]: label_name is y
[DEBUG] [2021-06-15 21:56:47,877] [3074:139995760379712] - profile.py[line:84]: [computing#f5cbdb5719]function_stack: [data_io.py:227]gen_data_instance <-[data_io.py:175]transform <-[io_check.py:31]_func <-[data_io.py:148]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 21:56:47,877] [3074:139995760379712] - profile.py[line:87]: [computing#f5cbdb5719]start
[DEBUG] [2021-06-15 21:56:52,076] [3074:139995760379712] - profile.py[line:93]: [computing#f5cbdb5719]done, elapse: 4.198853254318237, function: mapValues(self: Table(partition=4), func: function) -> Table(partition=4)
[DEBUG] [2021-06-15 21:56:52,079] [3074:139995760379712] - profile.py[line:84]: [computing#fba26d134a]function_stack: [io_check.py:34]_func <-[data_io.py:148]read_data <-[data_io.py:895]transform <-[model_base.py:98]run
[DEBUG] [2021-06-15 21:56:52,080] [3074:139995760379712] - profile.py[line:87]: [computing#fba26d134a]start
[DEBUG] [2021-06-15 21:56:52,085] [3074:139995760379712] - profile.py[line:93]: [computing#fba26d134a]done, elapse: 0.0059032440185546875, function: count(self: Table(partition=4)) -> int
[DEBUG] [2021-06-15 21:56:52,086] [3074:139995760379712] - io_check.py[line:35]: num row of input: 30000 -> num row of output: 30000
[ERROR] [2021-06-15 21:56:52,087] [3074:139995760379712] - task_executor.py[line:191]: fit & transform data' header should be same
Traceback (most recent call last):
  File "/fate/python/fate_flow/operation/task_executor.py", line 168, in run_task
    run_object.run(component_parameters_on_party, task_run_args)
  File "/fate/python/federatedml/model_base.py", line 98, in run
    this_data_output = func(*real_param)
  File "/fate/python/federatedml/util/data_io.py", line 895, in transform
    return self.reader.read_data(data_inst, "transform")
  File "/fate/python/federatedml/util/data_io.py", line 150, in read_data
    data_instance = data_overview.header_alignment(data_instance, fit_header)
  File "/fate/python/federatedml/statistic/data_overview.py", line 75, in header_alignment
    raise ValueError("fit & transform data' header should be same")
ValueError: fit & transform data' header should be same
[INFO] [2021-06-15 21:56:52,236] [3074:139995760379712] - task_executor.py[line:313]: report task 2021061521563264143218_dataio_0 0 host 9998 to driver
[INFO] [2021-06-15 21:56:52,236] [3074:139995760379712] - control_client.py[line:42]: request update job 2021061521563264143218 task 2021061521563264143218_dataio_0 0 on host 9998
[INFO] [2021-06-15 21:56:52,319] [3074:139995760379712] - task_executor.py[line:202]: task 2021061521563264143218_dataio_0 host 9998 start time: 2021-06-15 21:56:45
[INFO] [2021-06-15 21:56:52,319] [3074:139995760379712] - task_executor.py[line:204]: task 2021061521563264143218_dataio_0 host 9998 end time: 2021-06-15 21:56:52
[INFO] [2021-06-15 21:56:52,319] [3074:139995760379712] - task_executor.py[line:206]: task 2021061521563264143218_dataio_0 host 9998 takes 6.633s
[INFO] [2021-06-15 21:56:52,320] [3074:139995760379712] - task_executor.py[line:209]: Finish 2021061521563264143218 dataio_0 2021061521563264143218_dataio_0 0 host 9998 task failed
[INFO] [2021-06-15 21:56:52,342] [3074:139995760379712] - task_executor.py[line:313]: report task 2021061521563264143218_dataio_0 0 host 9998 to driver
[INFO] [2021-06-15 21:56:52,343] [3074:139995760379712] - control_client.py[line:42]: request update job 2021061521563264143218 task 2021061521563264143218_dataio_0 0 on host 9998
